// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Company struct {
	ID             uuid.UUID      `json:"id"`
	Cnpj           string         `json:"cnpj"`
	Name           string         `json:"name"`
	Street         sql.NullString `json:"street"`
	Number         sql.NullString `json:"number"`
	City           sql.NullString `json:"city"`
	State          sql.NullString `json:"state"`
	ZipCode        sql.NullString `json:"zip_code"`
	ApprovalStatus string         `json:"approval_status"`
	CreatedAt      time.Time      `json:"created_at"`
}

type CompanyOwner struct {
	ID            uuid.UUID    `json:"id"`
	Email         string       `json:"email"`
	Phone         string       `json:"phone"`
	Password      string       `json:"password"`
	CompanyID     uuid.UUID    `json:"company_id"`
	ConsentLgpdAt sql.NullTime `json:"consent_lgpd_at"`
	CreatedAt     time.Time    `json:"created_at"`
}

type Rating struct {
	ID            uuid.UUID      `json:"id"`
	ShiftID       uuid.UUID      `json:"shift_id"`
	FromCompanyID uuid.NullUUID  `json:"from_company_id"`
	FromVetID     uuid.NullUUID  `json:"from_vet_id"`
	ToCompanyID   uuid.NullUUID  `json:"to_company_id"`
	ToVetID       uuid.NullUUID  `json:"to_vet_id"`
	Score         int32          `json:"score"`
	Comment       sql.NullString `json:"comment"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Shift struct {
	ID                uuid.UUID      `json:"id"`
	CompanyID         uuid.UUID      `json:"company_id"`
	StartsAt          time.Time      `json:"starts_at"`
	EndsAt            time.Time      `json:"ends_at"`
	Type              string         `json:"type"`
	OfferedValueCents int64          `json:"offered_value_cents"`
	Requirements      sql.NullString `json:"requirements"`
	Description       sql.NullString `json:"description"`
	Location          sql.NullString `json:"location"`
	Status            string         `json:"status"`
	CreatedAt         time.Time      `json:"created_at"`
}

type ShiftCandidacy struct {
	ID              uuid.UUID `json:"id"`
	ShiftID         uuid.UUID `json:"shift_id"`
	ShiftVetID      uuid.UUID `json:"shift_vet_id"`
	Status          string    `json:"status"`
	InvitedByClinic bool      `json:"invited_by_clinic"`
	CreatedAt       time.Time `json:"created_at"`
}

type ShiftVet struct {
	ID             uuid.UUID    `json:"id"`
	Email          string       `json:"email"`
	Phone          string       `json:"phone"`
	Password       string       `json:"password"`
	FullName       string       `json:"full_name"`
	Cpf            string       `json:"cpf"`
	CrmvNumber     string       `json:"crmv_number"`
	CrmvState      string       `json:"crmv_state"`
	Specialties    []string     `json:"specialties"`
	ApprovalStatus string       `json:"approval_status"`
	ConsentLgpdAt  sql.NullTime `json:"consent_lgpd_at"`
	CreatedAt      time.Time    `json:"created_at"`
}
