// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (id, company_id, street, number, city, state, zip_code)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, street, number, city, state, zip_code, created_at
`

type CreateAddressParams struct {
	ID        uuid.UUID      `json:"id"`
	CompanyID uuid.UUID      `json:"company_id"`
	Street    sql.NullString `json:"street"`
	Number    sql.NullString `json:"number"`
	City      sql.NullString `json:"city"`
	State     sql.NullString `json:"state"`
	ZipCode   sql.NullString `json:"zip_code"`
}

// Addresses
func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, createAddress,
		arg.ID,
		arg.CompanyID,
		arg.Street,
		arg.Number,
		arg.City,
		arg.State,
		arg.ZipCode,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Street,
		&i.Number,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.CreatedAt,
	)
	return i, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (id, cnpj, name, approval_status)
VALUES ($1, $2, $3, $4)
RETURNING id, cnpj, name, approval_status, created_at
`

type CreateCompanyParams struct {
	ID             uuid.UUID     `json:"id"`
	Cnpj           string        `json:"cnpj"`
	Name           string        `json:"name"`
	ApprovalStatus AccountStatus `json:"approval_status"`
}

// Companies
func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany,
		arg.ID,
		arg.Cnpj,
		arg.Name,
		arg.ApprovalStatus,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Cnpj,
		&i.Name,
		&i.ApprovalStatus,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (id, token, email, user_type, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token, email, user_type, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	ID        uuid.UUID `json:"id"`
	Token     string    `json:"token"`
	Email     string    `json:"email"`
	UserType  UserType  `json:"user_type"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Password reset tokens
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken,
		arg.ID,
		arg.Token,
		arg.Email,
		arg.UserType,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.UserType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createShiftVeterinary = `-- name: CreateShiftVeterinary :one
INSERT INTO shift_veterinaries (id, email, phone, password, full_name, cpf, crmv_number, crmv_state, specialties, approval_status, consent_lgpd_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, email, phone, password, full_name, cpf, crmv_number, crmv_state, specialties, approval_status, consent_lgpd_at, created_at
`

type CreateShiftVeterinaryParams struct {
	ID             uuid.UUID             `json:"id"`
	Email          string                `json:"email"`
	Phone          string                `json:"phone"`
	Password       string                `json:"password"`
	FullName       string                `json:"full_name"`
	Cpf            string                `json:"cpf"`
	CrmvNumber     string                `json:"crmv_number"`
	CrmvState      string                `json:"crmv_state"`
	Specialties    []VeterinarySpecialty `json:"specialties"`
	ApprovalStatus AccountStatus         `json:"approval_status"`
	ConsentLgpdAt  sql.NullTime          `json:"consent_lgpd_at"`
}

// Shift veterinaries
func (q *Queries) CreateShiftVeterinary(ctx context.Context, arg CreateShiftVeterinaryParams) (ShiftVeterinary, error) {
	row := q.db.QueryRowContext(ctx, createShiftVeterinary,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.FullName,
		arg.Cpf,
		arg.CrmvNumber,
		arg.CrmvState,
		pq.Array(arg.Specialties),
		arg.ApprovalStatus,
		arg.ConsentLgpdAt,
	)
	var i ShiftVeterinary
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.FullName,
		&i.Cpf,
		&i.CrmvNumber,
		&i.CrmvState,
		pq.Array(&i.Specialties),
		&i.ApprovalStatus,
		&i.ConsentLgpdAt,
		&i.CreatedAt,
	)
	return i, err
}

const findAddressByCompanyID = `-- name: FindAddressByCompanyID :one
SELECT id, company_id, street, number, city, state, zip_code, created_at FROM addresses WHERE company_id = $1
`

func (q *Queries) FindAddressByCompanyID(ctx context.Context, companyID uuid.UUID) (Address, error) {
	row := q.db.QueryRowContext(ctx, findAddressByCompanyID, companyID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Street,
		&i.Number,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.CreatedAt,
	)
	return i, err
}

const findCompanyByCnpj = `-- name: FindCompanyByCnpj :one
SELECT id, cnpj, name, approval_status, created_at FROM companies WHERE cnpj = $1
`

func (q *Queries) FindCompanyByCnpj(ctx context.Context, cnpj string) (Company, error) {
	row := q.db.QueryRowContext(ctx, findCompanyByCnpj, cnpj)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Cnpj,
		&i.Name,
		&i.ApprovalStatus,
		&i.CreatedAt,
	)
	return i, err
}

const findCompanyByID = `-- name: FindCompanyByID :one
SELECT id, cnpj, name, approval_status, created_at FROM companies WHERE id = $1
`

func (q *Queries) FindCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRowContext(ctx, findCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Cnpj,
		&i.Name,
		&i.ApprovalStatus,
		&i.CreatedAt,
	)
	return i, err
}

const findCompanyOwnerByEmail = `-- name: FindCompanyOwnerByEmail :one
SELECT id, email, phone, password, company_id, consent_lgpd_at, created_at FROM company_owners WHERE email = $1
`

// Company owners
func (q *Queries) FindCompanyOwnerByEmail(ctx context.Context, email string) (CompanyOwner, error) {
	row := q.db.QueryRowContext(ctx, findCompanyOwnerByEmail, email)
	var i CompanyOwner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.CompanyID,
		&i.ConsentLgpdAt,
		&i.CreatedAt,
	)
	return i, err
}

const findCompanyOwnerByID = `-- name: FindCompanyOwnerByID :one
SELECT id, email, phone, password, company_id, consent_lgpd_at, created_at FROM company_owners WHERE id = $1
`

func (q *Queries) FindCompanyOwnerByID(ctx context.Context, id uuid.UUID) (CompanyOwner, error) {
	row := q.db.QueryRowContext(ctx, findCompanyOwnerByID, id)
	var i CompanyOwner
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.CompanyID,
		&i.ConsentLgpdAt,
		&i.CreatedAt,
	)
	return i, err
}

const findShiftVeterinaryByCpf = `-- name: FindShiftVeterinaryByCpf :one
SELECT id, email, phone, password, full_name, cpf, crmv_number, crmv_state, specialties, approval_status, consent_lgpd_at, created_at FROM shift_veterinaries WHERE cpf = $1
`

func (q *Queries) FindShiftVeterinaryByCpf(ctx context.Context, cpf string) (ShiftVeterinary, error) {
	row := q.db.QueryRowContext(ctx, findShiftVeterinaryByCpf, cpf)
	var i ShiftVeterinary
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.FullName,
		&i.Cpf,
		&i.CrmvNumber,
		&i.CrmvState,
		pq.Array(&i.Specialties),
		&i.ApprovalStatus,
		&i.ConsentLgpdAt,
		&i.CreatedAt,
	)
	return i, err
}

const findShiftVeterinaryByEmail = `-- name: FindShiftVeterinaryByEmail :one
SELECT id, email, phone, password, full_name, cpf, crmv_number, crmv_state, specialties, approval_status, consent_lgpd_at, created_at FROM shift_veterinaries WHERE email = $1
`

func (q *Queries) FindShiftVeterinaryByEmail(ctx context.Context, email string) (ShiftVeterinary, error) {
	row := q.db.QueryRowContext(ctx, findShiftVeterinaryByEmail, email)
	var i ShiftVeterinary
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.FullName,
		&i.Cpf,
		&i.CrmvNumber,
		&i.CrmvState,
		pq.Array(&i.Specialties),
		&i.ApprovalStatus,
		&i.ConsentLgpdAt,
		&i.CreatedAt,
	)
	return i, err
}

const findShiftVeterinaryByID = `-- name: FindShiftVeterinaryByID :one
SELECT id, email, phone, password, full_name, cpf, crmv_number, crmv_state, specialties, approval_status, consent_lgpd_at, created_at FROM shift_veterinaries WHERE id = $1
`

func (q *Queries) FindShiftVeterinaryByID(ctx context.Context, id uuid.UUID) (ShiftVeterinary, error) {
	row := q.db.QueryRowContext(ctx, findShiftVeterinaryByID, id)
	var i ShiftVeterinary
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.FullName,
		&i.Cpf,
		&i.CrmvNumber,
		&i.CrmvState,
		pq.Array(&i.Specialties),
		&i.ApprovalStatus,
		&i.ConsentLgpdAt,
		&i.CreatedAt,
	)
	return i, err
}

const findShiftVeterinaryByPhone = `-- name: FindShiftVeterinaryByPhone :one
SELECT id, email, phone, password, full_name, cpf, crmv_number, crmv_state, specialties, approval_status, consent_lgpd_at, created_at FROM shift_veterinaries WHERE phone = $1
`

func (q *Queries) FindShiftVeterinaryByPhone(ctx context.Context, phone string) (ShiftVeterinary, error) {
	row := q.db.QueryRowContext(ctx, findShiftVeterinaryByPhone, phone)
	var i ShiftVeterinary
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.FullName,
		&i.Cpf,
		&i.CrmvNumber,
		&i.CrmvState,
		pq.Array(&i.Specialties),
		&i.ApprovalStatus,
		&i.ConsentLgpdAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTokenByToken = `-- name: GetPasswordResetTokenByToken :one
SELECT id, token, email, user_type, expires_at, used_at, created_at FROM password_reset_tokens WHERE token = $1
`

func (q *Queries) GetPasswordResetTokenByToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetTokenByToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.UserType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, id)
	return err
}

const registerCompanyOwner = `-- name: RegisterCompanyOwner :exec
INSERT INTO company_owners (id, email, phone, password, company_id, consent_lgpd_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RegisterCompanyOwnerParams struct {
	ID            uuid.UUID    `json:"id"`
	Email         string       `json:"email"`
	Phone         string       `json:"phone"`
	Password      string       `json:"password"`
	CompanyID     uuid.UUID    `json:"company_id"`
	ConsentLgpdAt sql.NullTime `json:"consent_lgpd_at"`
}

func (q *Queries) RegisterCompanyOwner(ctx context.Context, arg RegisterCompanyOwnerParams) error {
	_, err := q.db.ExecContext(ctx, registerCompanyOwner,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.CompanyID,
		arg.ConsentLgpdAt,
	)
	return err
}

const updateCompanyOwnerPassword = `-- name: UpdateCompanyOwnerPassword :exec
UPDATE company_owners SET password = $2 WHERE id = $1
`

type UpdateCompanyOwnerPasswordParams struct {
	ID       uuid.UUID `json:"id"`
	Password string    `json:"password"`
}

func (q *Queries) UpdateCompanyOwnerPassword(ctx context.Context, arg UpdateCompanyOwnerPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateCompanyOwnerPassword, arg.ID, arg.Password)
	return err
}

const updateShiftVeterinaryPassword = `-- name: UpdateShiftVeterinaryPassword :exec
UPDATE shift_veterinaries SET password = $2 WHERE id = $1
`

type UpdateShiftVeterinaryPasswordParams struct {
	ID       uuid.UUID `json:"id"`
	Password string    `json:"password"`
}

func (q *Queries) UpdateShiftVeterinaryPassword(ctx context.Context, arg UpdateShiftVeterinaryPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateShiftVeterinaryPassword, arg.ID, arg.Password)
	return err
}
