export const VETERINARY_SPECIALTIES = [
  "general_practice",
  "felines",
  "wildlife",
  "dermatology",
  "cardiology",
  "nephrology",
  "urology",
  "endocrinology",
  "gastroenterology",
  "neurology",
  "orthopedics",
  "dentistry",
  "ophthalmology",
  "ultrasound",
  "pathology",
  "anesthesiology",
  "icu",
  "oncology",
  "physiotherapy",
  "behavioral",
] as const;

export const SPECIALTY_LABELS: Record<string, string> = {
  general_practice: "Clínico geral",
  felines: "Felinos",
  wildlife: "Silvestres",
  dermatology: "Dermatologia",
  cardiology: "Cardiologia",
  nephrology: "Nefrologia",
  urology: "Urologia",
  endocrinology: "Endocrinologia",
  gastroenterology: "Gastroenterologia",
  neurology: "Neurologia",
  orthopedics: "Ortopedia",
  dentistry: "Odontologia",
  ophthalmology: "Oftalmologia",
  ultrasound: "Ultrassom",
  pathology: "Patologia",
  anesthesiology: "Anestesiologia",
  icu: "UTI",
  oncology: "Oncologia",
  physiotherapy: "Fisioterapia",
  behavioral: "Comportamental",
};
